apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # ArgoCD Application 리소스는 root kustomization.yaml에서 관리
  # - argocd/metallb.yaml

  # MetalLB configuration
  - ipaddresspool.yaml
  - l2advertisement.yaml
