apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # ArgoCD Application 리소스는 infrastructure/kustomization.yaml에서 관리
  # - argocd/cert-manager.yaml
  # - argocd/cert-manager-issuers.yaml
  - cluster-issuer-prod.yaml
  - cluster-issuer-staging.yaml
